<?php

namespace Jukebox\JukeboxBundle\Entity;

/**
 * ArtistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistaRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLatestArtistas($limit = null)
  {
	   $qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.fecha_nacimiento', 'DESC');

	   if (false === is_null($limit))
		   $qp->setMaxResults($limit);

	   return $qp->getQuery()->getResult();
   }

}
